services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
  ui:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ui
    environment:
      - API_BASE=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ..:/app